USE disaster_relief_db;

START TRANSACTION;

-- Remove demo-only data generated by seed_demo.sql.

DELETE pe
FROM payment_events pe
JOIN payments p ON p.id = pe.payment_id
WHERE p.payment_order_id IN ('order_demo_2026_001', 'order_demo_2026_002', 'order_demo_2026_003');

DELETE dn
FROM donations dn
JOIN payments p ON p.id = dn.payment_id
WHERE p.payment_order_id IN ('order_demo_2026_001', 'order_demo_2026_002', 'order_demo_2026_003');

DELETE FROM notifications
WHERE title IN ('High Priority Flood Escalation', 'Medical Request Assigned', 'Inventory Shortage Alert', 'Donation Received');

DELETE FROM audit_logs
WHERE user_agent IN ('Mozilla/5.0 DemoOps', 'Mozilla/5.0 FieldCoordinator');

DELETE a
FROM assignments a
JOIN disasters d ON d.id = a.disaster_id
WHERE d.title IN (
  'Mumbai Monsoon Flooding - Kurla Cluster',
  'Mumbai Building Fire - Bhiwandi Warehouse',
  'Navi Mumbai Heatwave Impact',
  'Chennai Cyclone Surge - Marina Belt',
  'Chennai Flooding - Velachery Basin',
  'Cuddalore Landslide Trigger',
  'Kolkata Riverbank Flood Alert',
  'Guwahati Flash Flood - Beltola',
  'Dibrugarh Embankment Breach Response',
  'Bhubaneswar Earth Tremor Preparedness'
);

DELETE rr
FROM relief_requests rr
JOIN disasters d ON d.id = rr.disaster_id
WHERE d.title IN (
  'Mumbai Monsoon Flooding - Kurla Cluster',
  'Chennai Cyclone Surge - Marina Belt',
  'Guwahati Flash Flood - Beltola',
  'Dibrugarh Embankment Breach Response'
);

DELETE v
FROM victims v
JOIN disasters d ON d.id = v.disaster_id
WHERE d.title IN (
  'Mumbai Monsoon Flooding - Kurla Cluster',
  'Chennai Cyclone Surge - Marina Belt',
  'Guwahati Flash Flood - Beltola',
  'Dibrugarh Embankment Breach Response'
);

DELETE i
FROM inventory i
LEFT JOIN locations l ON l.id = i.location_id
WHERE i.item_name IN (
  'Ready-to-Eat Meal Pack',
  'Drinking Water 20L Can',
  'Chlorine Tablets',
  'Emergency Blanket',
  'ORS Sachets',
  'Inflatable Rescue Boat Fuel'
) AND (l.name IN (
  'Navi Mumbai Distribution Hub',
  'Mumbai Relief Camp - Sion',
  'Mumbai Shelter - Dharavi School',
  'Chennai Shelter - Velachery',
  'Chennai Medical Camp - Perungudi',
  'Guwahati Shelter - Beltola'
) OR l.name IS NULL);

DELETE FROM payments WHERE payment_order_id IN ('order_demo_2026_001', 'order_demo_2026_002', 'order_demo_2026_003');

DELETE FROM disasters
WHERE title IN (
  'Mumbai Monsoon Flooding - Kurla Cluster',
  'Mumbai Building Fire - Bhiwandi Warehouse',
  'Navi Mumbai Heatwave Impact',
  'Chennai Cyclone Surge - Marina Belt',
  'Chennai Flooding - Velachery Basin',
  'Cuddalore Landslide Trigger',
  'Kolkata Riverbank Flood Alert',
  'Guwahati Flash Flood - Beltola',
  'Dibrugarh Embankment Breach Response',
  'Bhubaneswar Earth Tremor Preparedness'
);

DELETE FROM volunteers
WHERE user_id IN (
  SELECT id FROM users WHERE username IN ('volunteer_mum_01', 'volunteer_mum_02', 'volunteer_che_01', 'volunteer_asm_01')
);

DELETE FROM user_roles
WHERE user_id IN (
  SELECT id FROM users WHERE username IN (
    'ops_lead_mumbai', 'ops_lead_chennai', 'volunteer_mum_01', 'volunteer_mum_02',
    'volunteer_che_01', 'volunteer_asm_01', 'citizen_mumbai_01', 'citizen_chennai_01',
    'citizen_kolkata_01', 'donor_corp_01', 'donor_ind_01'
  )
);

DELETE FROM users
WHERE username IN (
  'ops_lead_mumbai', 'ops_lead_chennai', 'volunteer_mum_01', 'volunteer_mum_02',
  'volunteer_che_01', 'volunteer_asm_01', 'citizen_mumbai_01', 'citizen_chennai_01',
  'citizen_kolkata_01', 'donor_corp_01', 'donor_ind_01'
);

DELETE FROM locations
WHERE name IN (
  'Mumbai Relief Camp - Sion',
  'Mumbai Shelter - Dharavi School',
  'Navi Mumbai Distribution Hub',
  'Chennai Shelter - Velachery',
  'Chennai Medical Camp - Perungudi',
  'Kolkata Relief Camp - Howrah',
  'Guwahati Shelter - Beltola'
);

COMMIT;
